title: BoxOffice2
description: "A website about box office information."
url: "https://asemabuothman.github.io"
baseurl: "/repository-name"  # Leave empty if it's your user page (e.g., https://username.github.io)

# Optional settings
theme: jekyll-theme-minimal
exclude:
  - README.md
  - LICENSE.md

# Custom settings
author:
  name: "Asem Abu Othman"
  email: "asemabuothman@gmail.com"

# Social media links
social:
  twitter: "https://twitter.com/asemabuothman"
  github: "https://github.com/asemabuothman"
  linkedin: "https://linkedin.com/in/asemabuothman"
